version: '3.7'

services:
    db:
        image: postgres:14-alpine
        environment:
          POSTGRES_USER: ${DATABASE_USER}
          POSTGRES_PASSWORD: ${DATABASE_PASS}
          POSTGRES_DB: ${DATABASE_NAME}
        volumes:
          - './data/postgres:/var/lib/postgresql/data:delegated'
        ports:
          - 5432:5432