version: '3.7'

services:
    db:
        image: postgres:14-alpine
        environment:
          POSTGRES_USER: ${DATABASE_USER}
          POSTGRES_PASSWORD: ${DATABASE_PASS}
          POSTGRES_DB: ${DATABASE_NAME}
        volumes:
          - './data/postgres:/var/lib/postgresql/data:delegated'
        ports:
          - 5432:5432

    backend:
      image: yiisoftware/yii2-php:7.1-apache
      volumes:
        - ./backend/composer/cache:/root/.composer/cache:delegated
        - ./backend/basic:/app:delegated
      environment:
        DATABASE_NAME: ${DATABASE_NAME}
        DATABASE_USER: ${DATABASE_USER}
        DATABASE_PASS: ${DATABASE_PASS}
        DATABASE_HOST: db
        PHP_USER_ID: ${PHP_USER_ID}
        PRODUCTION: ${AMBIENTE_DESARROLLO}
      ports:  
          - 8000:80